-- ============================================================================
-- CRUD de opciones de Sede / Módulo (correr UNA vez en Supabase -> SQL Editor).
--
-- 1) Agrega un id a cada opcion (hace falta para poder editar y eliminar una por una desde
--    el panel del administrador).
-- 2) Vuelve a cargar las opciones por defecto: la tabla quedo vacia (el editor anterior
--    reemplazaba la lista completa, y guardar con el cuadro vacio la borro). Si ya existen,
--    no se duplican. Despues se pueden editar/eliminar desde el panel.
--
-- Los registros viejos NO se ven afectados por editar o eliminar opciones: cada sesion guarda
-- la sede y el modulo como texto en `eventos_conexion` en el momento de conectarse.
-- Seguro de correr mas de una vez.
-- ============================================================================

alter table opciones_configurables
    add column if not exists id bigint generated by default as identity;

create unique index if not exists idx_opciones_configurables_id on opciones_configurables(id);

insert into opciones_configurables (tipo, valor, orden) values
    ('sede', 'Sede Principal', 0),
    ('sede', 'Campus Norte', 1),
    ('sede', 'Atención Virtual', 2),
    ('modulo', 'Admisiones y Registro', 0),
    ('modulo', 'Soporte Técnico', 1),
    ('modulo', 'Financiera', 2)
on conflict (tipo, valor) do nothing;
