-- ============================================================================
-- Diccionario de lenguaje inapropiado (Colombia) para Supabase.
-- Correr UNA vez en: Supabase -> SQL Editor -> New query.
--
-- Crea la tabla lenguaje_inapropiado y la llena con el diccionario inicial. Despues se
-- administra desde el panel: Historial y Reportes -> Diccionario de lenguaje inapropiado.
-- Seguro de correr mas de una vez (no duplica terminos).
--
-- Categorias:
--   groseria_fuerte : se detecta siempre.
--   groseria_leve   : solo con la sensibilidad en "estricto" (la de por defecto).
--   mal_trato       : frases que niegan la atencion o tratan mal al usuario; siempre.
-- ============================================================================

create table if not exists lenguaje_inapropiado (
    id serial primary key,
    termino text not null unique,
    categoria text not null check (categoria in ('groseria_fuerte', 'groseria_leve', 'mal_trato')),
    creado_en timestamptz not null default now()
);

insert into lenguaje_inapropiado (termino, categoria) values
    ('hijueputa', 'groseria_fuerte'),
    ('hijueputas', 'groseria_fuerte'),
    ('hijueputica', 'groseria_fuerte'),
    ('jueputa', 'groseria_fuerte'),
    ('hp', 'groseria_fuerte'),
    ('hpta', 'groseria_fuerte'),
    ('hptas', 'groseria_fuerte'),
    ('hijo de puta', 'groseria_fuerte'),
    ('hijos de puta', 'groseria_fuerte'),
    ('hija de puta', 'groseria_fuerte'),
    ('hijuemadre', 'groseria_fuerte'),
    ('gonorrea', 'groseria_fuerte'),
    ('gonorreas', 'groseria_fuerte'),
    ('gonorriento', 'groseria_fuerte'),
    ('gonorrienta', 'groseria_fuerte'),
    ('gonorrio', 'groseria_fuerte'),
    ('malparido', 'groseria_fuerte'),
    ('malparida', 'groseria_fuerte'),
    ('malparidos', 'groseria_fuerte'),
    ('malparidas', 'groseria_fuerte'),
    ('malnacido', 'groseria_fuerte'),
    ('malnacida', 'groseria_fuerte'),
    ('carechimba', 'groseria_fuerte'),
    ('careverga', 'groseria_fuerte'),
    ('carepicha', 'groseria_fuerte'),
    ('culicagado', 'groseria_fuerte'),
    ('culicagada', 'groseria_fuerte'),
    ('pirobo', 'groseria_fuerte'),
    ('piroba', 'groseria_fuerte'),
    ('pirobos', 'groseria_fuerte'),
    ('me vale verga', 'groseria_fuerte'),
    ('vale verga', 'groseria_fuerte'),
    ('puta', 'groseria_fuerte'),
    ('putas', 'groseria_fuerte'),
    ('puto', 'groseria_fuerte'),
    ('putos', 'groseria_fuerte'),
    ('mierda', 'groseria_fuerte'),
    ('mierdas', 'groseria_fuerte'),
    ('comemierda', 'groseria_fuerte'),
    ('come mierda', 'groseria_fuerte'),
    ('verga', 'groseria_fuerte'),
    ('vergas', 'groseria_fuerte'),
    ('coño', 'groseria_fuerte'),
    ('cabron', 'groseria_fuerte'),
    ('cabrona', 'groseria_fuerte'),
    ('cabrones', 'groseria_fuerte'),
    ('culo', 'groseria_fuerte'),
    ('culero', 'groseria_fuerte'),
    ('zorra', 'groseria_fuerte'),
    ('perra', 'groseria_fuerte'),
    ('maricon', 'groseria_fuerte'),
    ('maricona', 'groseria_fuerte'),
    ('maricones', 'groseria_fuerte'),
    ('chupamela', 'groseria_fuerte'),
    ('chupala', 'groseria_fuerte'),
    ('mamaguevo', 'groseria_fuerte'),
    ('mamaguevos', 'groseria_fuerte'),
    ('hijo de perra', 'groseria_fuerte'),
    ('vete a la mierda', 'groseria_fuerte'),
    ('vayase a la mierda', 'groseria_fuerte'),
    ('que se joda', 'groseria_fuerte'),
    ('jodase', 'groseria_fuerte'),
    ('marica', 'groseria_leve'),
    ('maricas', 'groseria_leve'),
    ('guevon', 'groseria_leve'),
    ('guevona', 'groseria_leve'),
    ('huevon', 'groseria_leve'),
    ('huevona', 'groseria_leve'),
    ('gueva', 'groseria_leve'),
    ('guevas', 'groseria_leve'),
    ('idiota', 'groseria_leve'),
    ('idiotas', 'groseria_leve'),
    ('imbecil', 'groseria_leve'),
    ('imbeciles', 'groseria_leve'),
    ('estupido', 'groseria_leve'),
    ('estupida', 'groseria_leve'),
    ('estupidos', 'groseria_leve'),
    ('pendejo', 'groseria_leve'),
    ('pendeja', 'groseria_leve'),
    ('pendejos', 'groseria_leve'),
    ('pendejada', 'groseria_leve'),
    ('bobo', 'groseria_leve'),
    ('boba', 'groseria_leve'),
    ('bobos', 'groseria_leve'),
    ('tarado', 'groseria_leve'),
    ('tarada', 'groseria_leve'),
    ('bruto', 'groseria_leve'),
    ('bruta', 'groseria_leve'),
    ('brutos', 'groseria_leve'),
    ('baboso', 'groseria_leve'),
    ('babosa', 'groseria_leve'),
    ('lambon', 'groseria_leve'),
    ('lambona', 'groseria_leve'),
    ('chandoso', 'groseria_leve'),
    ('chandosa', 'groseria_leve'),
    ('ñero', 'groseria_leve'),
    ('ñera', 'groseria_leve'),
    ('gamin', 'groseria_leve'),
    ('gamina', 'groseria_leve'),
    ('mamon', 'groseria_leve'),
    ('mamona', 'groseria_leve'),
    ('maldito', 'groseria_leve'),
    ('maldita', 'groseria_leve'),
    ('malditos', 'groseria_leve'),
    ('carajo', 'groseria_leve'),
    ('joder', 'groseria_leve'),
    ('jodido', 'groseria_leve'),
    ('jodida', 'groseria_leve'),
    ('no joda', 'groseria_leve'),
    ('inutil', 'groseria_leve'),
    ('inutiles', 'groseria_leve'),
    ('incompetente', 'groseria_leve'),
    ('ignorante', 'groseria_leve'),
    ('no lo puedo ayudar', 'mal_trato'),
    ('no la puedo ayudar', 'mal_trato'),
    ('no los puedo ayudar', 'mal_trato'),
    ('no lo puedo ayudar con su solicitud', 'mal_trato'),
    ('no la puedo ayudar con su solicitud', 'mal_trato'),
    ('no puedo ayudarlo', 'mal_trato'),
    ('no puedo ayudarla', 'mal_trato'),
    ('no puedo hacer nada por usted', 'mal_trato'),
    ('no puedo hacer nada por ti', 'mal_trato'),
    ('averigue en otro lado', 'mal_trato'),
    ('averigue en otra parte', 'mal_trato'),
    ('vaya a averiguar en otro lado', 'mal_trato'),
    ('pregunte en otro lado', 'mal_trato'),
    ('busque a otro', 'mal_trato'),
    ('no me pregunte eso', 'mal_trato'),
    ('no me pregunte a mi', 'mal_trato'),
    ('eso no es conmigo', 'mal_trato'),
    ('eso no es mi problema', 'mal_trato'),
    ('no es mi problema', 'mal_trato'),
    ('ese no es mi problema', 'mal_trato'),
    ('no es mi trabajo', 'mal_trato'),
    ('no es asunto mio', 'mal_trato'),
    ('eso no me compete', 'mal_trato'),
    ('eso no me corresponde', 'mal_trato'),
    ('yo no tengo la culpa', 'mal_trato'),
    ('a mi que me importa', 'mal_trato'),
    ('no me interesa su problema', 'mal_trato'),
    ('arreglese como pueda', 'mal_trato'),
    ('arreglatelas como puedas', 'mal_trato'),
    ('hagale como quiera', 'mal_trato'),
    ('haga lo que quiera', 'mal_trato'),
    ('resuelva usted mismo', 'mal_trato'),
    ('resuelvalo usted', 'mal_trato'),
    ('no tengo tiempo para esto', 'mal_trato'),
    ('no tengo tiempo para usted', 'mal_trato'),
    ('deje de molestar', 'mal_trato'),
    ('no me moleste', 'mal_trato'),
    ('no vuelva a molestarme', 'mal_trato'),
    ('que fastidio con usted', 'mal_trato'),
    ('usted no entiende nada', 'mal_trato'),
    ('no le puedo dar esa informacion', 'mal_trato')
on conflict (termino) do nothing;
